import test from 'node:test';
import assert from 'node:assert/strict';
import { readFile } from 'node:fs/promises';
import { generateKeyPair, SignJWT } from 'jose';
import { createLoginVerifier } from '../src/verify-login.mjs';
const config=JSON.parse(await readFile(new URL('../aleph.config.json',import.meta.url)));
const id='11111111-1111-4111-8111-111111111111';
test('judge signature, issuer and audience are validated without modifying verifier',async()=>{const {privateKey,publicKey}=await generateKeyPair('ES256');const verify=createLoginVerifier({config,judgeKeySet:async()=>publicKey,supabaseClient:{auth:{getClaims:async()=>{throw Error('not student');}}}});const now=Math.floor(Date.now()/1000);const token=await new SignJWT({aleph_run:'22222222-2222-4222-8222-222222222222',aleph_role:'judge',aleph_identity:'a'}).setProtectedHeader({alg:'ES256'}).setIssuer(config.judgeIssuer).setAudience(new URL(config.publicAppUrl).hostname).setSubject(id).setIssuedAt(now).setExpirationTime(now+300).sign(privateKey);assert.equal((await verify('Bearer '+token)).userId,id);assert.equal(await verify('Bearer '+token.slice(0,-10)+'aaaaaaaaaa'),null);assert.equal(await verify('Bearer invalid'),null);assert.equal(await verify(null),null);});
test('student claims must be verified by official SDK and match expected issuer/role',async()=>{const {privateKey}=await generateKeyPair('ES256');const token=await new SignJWT({}).setProtectedHeader({alg:'ES256'}).setIssuer(config.identityProvider.issuer).sign(privateKey);let claims={iss:config.identityProvider.issuer,aud:'authenticated',role:'authenticated',sub:id,exp:Math.floor(Date.now()/1000)+300};let failure=false;const verify=createLoginVerifier({config,judgeKeySet:async()=>null,supabaseClient:{auth:{getClaims:async()=>({data:{claims},error:failure?{}:null})}}});assert.equal((await verify('Bearer '+token)).userId,id);failure=true;assert.equal(await verify('Bearer '+token),null);failure=false;claims={...claims,role:'service_role'};assert.equal(await verify('Bearer '+token),null);});
