import test from 'node:test';
import assert from 'node:assert/strict';
import { createNotesHandler } from '../src/notes-handler.mjs';
import handler from '../api/notes.js';
const A='11111111-1111-4111-8111-111111111111';
const B='22222222-2222-4222-8222-222222222222';
const ID='33333333-3333-4333-8333-333333333333';
function response(){return {headers:{},setHeader(k,v){this.headers[k]=v;},status(code){this.code=code;return this;},json(body){this.body=body;return this;}};}
function database(){const rows=new Map();return {rows,from(name){assert.equal(name,'user_notes');let operation='select',values;const filters=[];const q={select(){return q;},eq(k,v){filters.push([k,v]);return q;},insert(v){operation='insert';values=v;return q;},update(v){operation='update';values=v;return q;},delete(){operation='delete';return q;},async order(){return {data:[...rows.values()].filter(r=>filters.every(([k,v])=>r[k]===v)).map(({id,title,body})=>({id,title,body})),error:null};},async maybeSingle(){let row;if(operation==='insert'){if(rows.has(values.id))return {error:{code:'23505'}};row={...values};rows.set(row.id,row);}else{row=[...rows.values()].find(r=>filters.every(([k,v])=>r[k]===v));if(row&&operation==='update')Object.assign(row,values);if(row&&operation==='delete')rows.delete(row.id);}return {data:row?{id:row.id,title:row.title,body:row.body}:null,error:null};}};return q;}};}
test('unauthenticated API fails closed before runtime and never exposes server detail',async()=>{const res=response();await handler({method:'GET'},res);assert.equal(res.code,401);assert.deepEqual(res.body,{error:'login_required'});assert.equal(res.headers['X-Content-Type-Options'],'nosniff');const failed=response();await createNotesHandler(()=>{throw new Error('private upstream detail');})({method:'GET',headers:{authorization:'Bearer invalid'}},failed);assert.equal(failed.code,503);assert.deepEqual(failed.body,{error:'auth_unavailable'});const invalid=response();await createNotesHandler(()=>({verify:async()=>null}))({method:'GET',headers:{authorization:'Bearer invalid'}},invalid);assert.equal(invalid.code,401);});
test('verified identity controls ownership; CRUD contract and deleted GET404',async()=>{const db=database();const h=createNotesHandler(()=>({db,verify:async auth=>auth==='Bearer fixtureA'?{userId:A}:auth==='Bearer fixtureB'?{userId:B}:null}));const call=async(method,id,body,identity='A')=>{const res=response();await h({method,query:id?{id}:{},body,headers:{authorization:'Bearer fixture'+identity}},res);return res;};const made=await call('POST',null,{id:ID,title:'Fixture',body:'Disposable test text',userId:B,role:'admin'});assert.equal(made.code,201);assert.deepEqual(made.body,{id:ID});assert.equal(db.rows.get(ID).owner_id,A);assert.equal((await call('GET')).body.length,1);assert.deepEqual((await call('GET',null,null,'B')).body,[]);assert.equal((await call('GET',ID)).body.title,'Fixture');assert.equal((await call('PUT',ID,{title:'Changed',body:'Updated'})).code,200);assert.equal(db.rows.get(ID).owner_id,A);assert.equal((await call('GET',ID,null,'B')).code,404);assert.equal((await call('PUT',ID,{title:'Attack',body:'Attack'},'B')).code,404);assert.equal((await call('DELETE',ID,null,'B')).code,404);assert.equal((await call('PUT',ID,{title:'Attack',body:'Attack',owner_id:B})).code,403);assert.equal(db.rows.get(ID).title,'Changed');assert.equal((await call('POST',null,{title:'Attack',body:'Attack',owner_id:B})).code,403);assert.equal((await call('POST',null,{id:ID,title:'Duplicate',body:''})).code,409);assert.equal((await call('PUT',ID,{title:'',body:''})).code,400);assert.equal((await call('DELETE',ID)).code,200);assert.equal((await call('GET',ID)).code,404);assert.equal((await call('GET','not-uuid')).code,400);const bNote=await call('POST',null,{title:'B fixture',body:'B text'},'B');assert.equal(bNote.code,201);assert.equal(db.rows.get(bNote.body.id).owner_id,B);assert.equal((await call('GET',bNote.body.id,null,'A')).code,404);assert.equal((await call('PUT',bNote.body.id,{title:'B changed',body:'B update'},'B')).code,200);assert.equal((await call('DELETE',bNote.body.id,null,'B')).code,200);});
